# Generated by Django 5.0.1 on 2024-02-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_author_total_rating_alter_book_total_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='total_rating',
        ),
        migrations.AddField(
            model_name='author',
            name='total_books',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='author',
            name='total_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
