# Generated by Django 5.0.1 on 2024-02-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_total_rating_author_total_books_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='total_books',
        ),
        migrations.RemoveField(
            model_name='book',
            name='average_rating',
        ),
        migrations.AddField(
            model_name='book',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='author',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
