# Generated by Django 5.0.1 on 2024-02-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_author_average_rating_book_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
