# Generated by Django 5.0.1 on 2024-02-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_total_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='author',
            name='total_rating',
        ),
    ]
