# Generated by Django 5.0.1 on 2024-02-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_remove_author_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='author',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
